// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvudnzdoekasbetcawga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dWRuemRvZWthc2JldGNhd2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzA2NTIsImV4cCI6MjA2NDU0NjY1Mn0.kI6D-QE4Ne8twXpzfVVSz6aQNFq3zws1RPYCyBayrxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);